#pragma once

#define NFCGOESBRR_ABOUT_TEXT              \
    "XAXAAXAXAXAXAXAXAXAXAXAXAXAxa\n"      \
    "XAXAAXAXAXAXAXAXAXAXAXAXAXAxax\n"     \
    "XAXAAXAXAXAXAXAXAXAXAXAXAXAxaxa\n"    \
    "XAXAAXAXAXAXAXAXAXAXAXAXAXAxaxax\n"   \
    "XAXAAXAXAXAXAXAXAXAXAXAXAXAxaxaxa\n"  \
    "XAXAXAXAXAXAXAXAXAXAXAXAXAXaxaxaxa\n" \
    "XAXAAXAXAXAXAXAXAXAXAXAXAXAxaxaxaxa"
